CREATE TABLE clients
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    email        VARCHAR(255),
    phone_number VARCHAR(255),
    address      VARCHAR(255),
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE invoices
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id      BIGINT                                  NOT NULL,
    amount         DECIMAL,
    description    VARCHAR(255),
    date_emission  date,
    date_paiement  date,
    status         VARCHAR(255),
    payment_method VARCHAR(255),
    CONSTRAINT pk_invoices PRIMARY KEY (id)
);

ALTER TABLE invoices
    ADD CONSTRAINT FK_INVOICES_ON_CLIENTID FOREIGN KEY (client_id) REFERENCES clients (id);